version: '0.1'
services:
  development:
    build: ./
    entrypoint: npm run dev
    ports:
      - '8080:8080'
      - '8081:8081'
      - '3001:3001'
    volumes:
      - ./example_project:/home/namics
      - /home/namics/node_modules
      - /home/namics/app
      - /home/namics/config
      - /home/namics/gulp
      - /home/namics/project
      - /home/namics/tests
      - /home/namics/node_modules/node-sass/vendor